repository_type: pipeline

nf_core_version: 3.4.1

lint:
  files_unchanged:
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-oceanomics-oceangenomes-genomenotes_logo_light.png
    - docs/images/nf-core-oceanomics-oceangenomes-genomenotes_logo_light.png
    - docs/images/nf-core-oceanomics-oceangenomes-genomenotes_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - CODE_OF_CONDUCT.md
    - assets/nf-core-oceanomics-oceangenomes-genomenotes_logo_light.png
    - docs/images/nf-core-oceanomics-oceangenomes-genomenotes_logo_light.png
    - docs/images/nf-core-oceanomics-oceangenomes-genomenotes_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml

template:
  org: LaurenHuet
  name: oceanomics-oceangenomes-genomenotes
  description: This pipeline is for the generation of the Minderoo OceanOmics centre
    high quality reference genomenotes.
  author: LaurenHuet
  version: 1.0.0
  force: true
  outdir: .
  skip_features:
    - igenomes
    - gpu
    - slackreport
  is_nfcore: false
